# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
   # If you want to run a single hook, execute `pre-commit run <hook-id>`.
   # For example, `pre-commit run trailing-whitespace` to run the trailing-whitespace hook manually
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-yaml
    - id: check-added-large-files
    - id: pretty-format-json

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
      args: ['--manifest-path', 'rust/Cargo.toml']
      files: '\.rs$'

# Add our own local hooks.
- repo: local
  hooks:
  # This hook invokes the typo checker backed by the `typos-cli` crate.
  # You need to ensure this crate is installed already.
  - id: typos
    name: typos
    entry: typos
    language: system

  # This hook invokes the toml checker backed by the `taplo-cli` crate.
  # You need to ensure this crate is installed already.
  - id: taplo
    name: taplo
    entry: taplo format
    language: system
